services:
  api:
    build:
      context: .
      dockerfile: VacinaApi/Dockerfile
    ports:
      - "5139:8080"
    volumes:
      - ./VacinaApi/vacinas.db:/app/vacinas.db
  api-dev:
    build:
      context: .
      dockerfile: VacinaApi/Dockerfile
    command: dotnet watch run --urls http://0.0.0.0:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5139:8080"
    volumes:
      - ./VacinaApi/vacinas.db:/app/vacinas.db
