include:
  - vacina-front/docker-compose.yaml
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5139:8080"
    volumes:
      - ./VacinaApi/vacinas.db:/app/vacinas.db
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: dotnet watch run --urls http://0.0.0.0:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5139:8080"
    volumes:
      - ./VacinaApi:/src/VacinaAPI
      - ./VacinaApi/vacinas.db:/src/VacinaAPI/vacinas.db
